### ISSUE TITLE
CompletionStage and vertx context.

### ISSUE THREAD

**Issue by javadevmtl** [bmsantos/vertx-graphql-example#6]
Hi I was looking through your code as I wanted to start testing out GraphQL. The part where the query are executed with the CompletionStage... Is it guaranteed to be running on the proper eventloop context?

I think you may have to wrap with context.runOnContext();

Referring to this part of the code...

```
final CompletionStage<ExecutionResult> future =
          graphQL.engine().executeAsync(query, operationName, new DataLoaders(restClient), variables);

future.handle((result, throwable) -> {
          final String doc = Json.encode(result);
          ctx.response().headers().set("Content-Type", "application/json");
          ctx.response().end(doc);
          return this;
        }).toCompletableFuture();
```

See this discussion here: https://mail.google.com/mail/u/0/#inbox/15ba5a10d99650d2

**Comment by a-marcel** [comment]
This google mail links is not working anymore.

M

**Comment by javadevmtl** [comment]
Oops here: https://groups.google.com/forum/?fromgroups#!topic/vertx/MPkxdFizxV0

**Comment by bmsantos** [comment]
@javadevmtl, sorry for the late answer. The intention here is to have the event loop complete the request response as there is no need (at least in my view), to have the GraphQL response handled in a different thread. The event-loop should lazily handle the response once the result from the Future is ready.

As long as you don't block the event-loop thread in the GraphQL Resolvers/DataLoaders, this code should work just fine in the event-loop threads. Try to print the threads and use JVisualVM to visualize the different type of threads used by the process. If I recall, you should see worker threads used by Vert.x HTTP client and Event-loop threads used for GraphQL request/response handling.

**Comment by bmsantos** [comment]
So, to actually answer to your question, yes, the code runs on the event-loop thread as part of the GraphQL HTTP request handler.

**Comment by javadevmtl** [comment]
Ok cool

**Comment by bmsantos** [comment]
@javadevmtl,

If you think this is still an issue because you are observing some oddities please let me know. Otherwise, just go ahead and close the issue or let me know so I can close it.

Cheers
